##################################################################################################
# ##################################### BY: Dalker(Tarzan) ##################################### #
# ############################################################################################## #
# ############ Copyright (C) 2020 | depascaldc - Management | All Rights Reserved ############## #
# ############################################################################################## #
##################################################################################################

name: SwimPlugin
main: fr.Tarzan.Main
version: "1.0.0"
api: "1.0.11"
author: Dalker(Tarzan)
